### ISSUE TITLE
Error running the test

### ISSUE THREAD

**Issue by hamid13r** [SBC-Utrecht/pytom-template-matching-gpu#25]
Hi,

I just installed pytom_tm, we use micromamba so I had to install cupy from conda-forge `conda install -c conda-forge cupy`. I still get an error when running the tests:

```
> ...Progress job_0 on device 0:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:01<00:00, 217.84it/s]
> .WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> Progress job_0 on device 0:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:01<00:00, 243.14it/s]
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> DEBUG:root:Next fast fft shape: (100, 45, 60)
> Progress job_00 on device 0:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:01<00:00, 237.16it/s]
> DEBUG:root:Next fast fft shape: (100, 48, 60)
> Progress job_01 on device 0:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:01<00:00, 249.47it/s]
> DEBUG:root:Next fast fft shape: (100, 45, 60)
> Progress job_02 on device 0:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:01<00:00, 249.58it/s]
> FWARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> .WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> .WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> Progress job_00 on device 0:
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 86/86 [00:00<00:00, 313.17it/s]
> Progress job_01 on device 0:
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85/85 [00:00<00:00, 300.09it/s]
> Progress job_02 on device 0:
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85/85 [00:00<00:00, 294.53it/s]
> FWARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> Progress job_00 on device 0:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:01<00:00, 250.95it/s]
> Progress job_01 on device 0:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:01<00:00, 253.99it/s]
> Progress job_02 on device 0:
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:01<00:00, 251.18it/s]
> F...
> ======================================================================
> FAIL: test_parallel_manager (test_tmjob.TestTMJob.test_parallel_manager)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/janlevinson/pytom-template-matching-gpu/tests/test_tmjob.py", line 198, in test_parallel_manager
>     self.assertTrue(angle_diff == 83., msg='angle diff should not change')
> AssertionError: False is not true : angle diff should not change
> 
> ======================================================================
> FAIL: test_tm_job_split_angles (test_tmjob.TestTMJob.test_tm_job_split_angles)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/janlevinson/pytom-template-matching-gpu/tests/test_tmjob.py", line 178, in test_tm_job_split_angles
>     self.assertTrue(np.abs(angle - read_mrc(TEST_ANGLES)).sum() == 0,
> AssertionError: False is not true : split rotation search should be identical
> 
> ======================================================================
> FAIL: test_tm_job_split_volume (test_tmjob.TestTMJob.test_tm_job_split_volume)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/janlevinson/pytom-template-matching-gpu/tests/test_tmjob.py", line 153, in test_tm_job_split_volume
>     self.assertTrue(angle_diff == 83., msg='angle diff should not change')
> AssertionError: False is not true : angle diff should not change
> 
> ----------------------------------------------------------------------
> Ran 12 tests in 15.801s
> 
> FAILED (failures=3)
> 
```

Seems like it fails when trying to run in parallel so it might not be a problem for us. Our tomogram fit in the GPU ram at bin8. But I was wondering if I am doing anything wrong. 

Best,
Hamid

**Comment by McHaillet** [comment]
Hi Hamid,

That is a bit strange. To clarify, the test checks that splitting the search in multiple tasks gives identical score and angle volumes back. The task split can be done by splitting the angular search or by splitting the volume into subvolumes. At least the angular search split I would assume to be very stable (for me the results are identical), but the volume split can change the results very slightly due to different weighting interpolation (which is why it should be equal to 83. when i tested it). I think the test should be more lenient for different systems due to small numerical changes. That would explain the errors in test_parallel_manager and test_tm_job_split_volume at least.

The good thing is though, the tests also check if the object is found back at the right orientation and right position, which is the case for all of your tests. So it might very well be that the second part of the tests are too stringent for different systems due to tiny numerical differences.

So I think the installation is fine for you, also for the parallel part. I will need to make a PR to make the tests a bit more lenient is suspect.

Best, Marten

**Comment by McHaillet** [comment]
To get some idea of what migth cause a difference, could you tell me the following?
- system that you are running on
- cuda version
- cupy version

**Comment by hamid13r** [comment]
Thank you for the quick response. I am Running on ubuntu 
`Linux janlevinson 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
`
On an RTX A5000 GPU and here is the environment I created:

List of packages in environment: "/home/janlevinson/micromamba/envs/pytom_tm"

```
  Name              Version    Build                Channel    
─────────────────────────────────────────────────────────────────
  _libgcc_mutex     0.1        conda_forge          conda-forge
  _openmp_mutex     4.5        2_gnu                conda-forge
  bzip2             1.0.8      h7f98852_4           conda-forge
  ca-certificates   2023.7.22  hbcca054_0           conda-forge
  cuda-version      11.8       h70ddcb2_2           conda-forge
  cudatoolkit       11.8.0     h4ba93d1_12          conda-forge
  cupy              12.2.0     py311h2bc1b5c_1      conda-forge
  fastrlock         0.8.2      py311hb755f60_0      conda-forge
  ld_impl_linux-64  2.40       h41732ed_0           conda-forge
  libblas           3.9.0      17_linux64_openblas  conda-forge
  libcblas          3.9.0      17_linux64_openblas  conda-forge
  libexpat          2.5.0      hcb278e6_1           conda-forge
  libffi            3.4.2      h7f98852_5           conda-forge
  libgcc-ng         13.1.0     he5830b7_0           conda-forge
  libgfortran-ng    13.1.0     h69a702a_0           conda-forge
  libgfortran5      13.1.0     h15d22d2_0           conda-forge
  libgomp           13.1.0     he5830b7_0           conda-forge
  liblapack         3.9.0      17_linux64_openblas  conda-forge
  libnsl            2.0.0      h7f98852_0           conda-forge
  libopenblas       0.3.23     pthreads_h80387f5_0  conda-forge
  libsqlite         3.43.0     h2797004_0           conda-forge
  libstdcxx-ng      13.1.0     hfd8a6a1_0           conda-forge
  libuuid           2.38.1     h0b41bf4_0           conda-forge
  libzlib           1.2.13     hd590300_5           conda-forge
  ncurses           6.4        hcb278e6_0           conda-forge
  numpy             1.25.2     py311h64a7726_0      conda-forge
  openssl           3.1.2      hd590300_0           conda-forge
  pip               23.2.1     pyhd8ed1ab_0         conda-forge
  python            3.11.5     hab00c5b_0_cpython   conda-forge
  python_abi        3.11       3_cp311              conda-forge
  readline          8.2        h8228510_1           conda-forge
  setuptools        68.1.2     pyhd8ed1ab_0         conda-forge
  tk                8.6.12     h27826a3_0           conda-forge
  tzdata            2023c      h71feb2d_0           conda-forge
  wheel             0.41.2     pyhd8ed1ab_0         conda-forge
  xz                5.2.6      h166bdaf_0           conda-forge

```

**Comment by McHaillet** [comment]
Your cupy version is identical to mine. Maybe different GPU is causing a difference, compared with my RTX 3060.
Will need to look further at it

**Comment by McHaillet** [comment]
Turns out I also get an issue on our cluster with similar cupy but different GPUs (GTX 1080 Ti).
I found out the issue comes from the template being a symmetrical object, resulting in a position in the volume getting multiple different angles assigned with identical scores. So I made a PR #40 for it now.
Will let you know once it is merged to the main repo and would be much appreciated if you could check then if the unittests pass for you.

**Comment by McHaillet** [comment]
PR #40 has been merged, could you give it another go on your system?

**Comment by hamid13r** [comment]
Got it, the error is gone!

> > python -m unittest discover
> ...Progress job_0 on device 0:
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1534.32it/s]
> .Progress job_0 on device 0:
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1561.57it/s]
> DEBUG:root:Next fast fft shape: (100, 45, 60)
> Progress job_00 on device 0:
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1524.72it/s]
> DEBUG:root:Next fast fft shape: (100, 48, 60)
> Progress job_01 on device 0:
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1570.49it/s]
> DEBUG:root:Next fast fft shape: (100, 45, 60)
> Progress job_02 on device 0:
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1561.32it/s]
> ...Progress job_00 on device 0:
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 86/86 [00:00<00:00, 1560.30it/s]
> Progress job_01 on device 0:
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85/85 [00:00<00:00, 1569.23it/s]
> Progress job_02 on device 0:
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85/85 [00:00<00:00, 1560.76it/s]
> .Progress job_00 on device 0:
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1573.68it/s]
> Progress job_01 on device 0:
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1579.62it/s]
> Progress job_02 on device 0:
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1577.16it/s]
> ....
> ----------------------------------------------------------------------
> Ran 12 tests in 4.583s
> 
> OK
