### ISSUE TITLE
Voxel size not identical error

### ISSUE THREAD

**Issue by hamid13r** [SBC-Utrecht/pytom-template-matching-gpu#26]
Hi,

I get this error "Input tomogram voxel spacing is not identical in each dimension!" when I use tomograms generated in WARP. But the template matching runs with IMOD generated tomos. 

Is there a way of forcing the pixel size?

pytom_match_template.py  -t 50S_ref.mrc -m 50S_mask.mrc -v tomo/JTL013_1_L04_ts_003.mrc_13.28Apx.mrc -a tomo/JTL014_1_L14_ts_003.mrc.tlt --angular-search 7.00 --search-x 10 500 --search-y 10 710 --search-z 10 210  --voxel-size-angstrom  13.28 --low-pass 40 --high-pass 500 -g 0 --log info

> Traceback (most recent call last):
>   File "/home/janlevinson/micromamba/envs/pytom_tm/bin/pytom_match_template.py", line 92, in <module>
>     main()
>   File "/home/janlevinson/micromamba/envs/pytom_tm/bin/pytom_match_template.py", line 62, in main
>     job = TMJob(
>           ^^^^^^
>   File "/home/janlevinson/micromamba/envs/pytom_tm/lib/python3.11/site-packages/pytom_tm/tmjob.py", line 83, in __init__
>     meta_data_tomo = read_mrc_meta_data(self.tomogram)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/janlevinson/micromamba/envs/pytom_tm/lib/python3.11/site-packages/pytom_tm/io.py", line 82, in read_mrc_meta_data
>     raise ValueError('Input tomogram voxel spacing is not identical in each dimension!')
> ValueError: Input tomogram voxel spacing is not identical in each dimension!

I also get a warning when specifying `--input-voxel-size-angstrom` for `pytom_create_template.py` saying

`WARNING:root:Provided voxel size does not match voxel size annotated in input map.`
And they might be related?

Thank you for your help in advance,
Hamid

**Comment by hamid13r** [comment]
Update:
I used 
`alterheader tomo/JTL013_1_L04_ts_003.mrc_13.28Apx.mrc -cel 512,722,226`
which changes the pixel size to 1,1,1 in the header. This overcomes the previous error and I only get a warning. 
```

> 
> pytom_match_template.py  -t 50S_ref.mrc -m 50S_mask.mrc -v tomo/JTL014_1_L14_ts_003.mrc_rec.mrc -a tomo/JTL014_1_L14_ts_003.mrc.tlt --angular-search 7.00 --search-x 10 500 --search-y 10 710 --search-z 10 210  --voxel-size-angstrom  13.28 --low-pass 40 --high-pass 500 -g 0 --log info
> WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> 

```

**Comment by McHaillet** [comment]
> I get this error "Input tomogram voxel spacing is not identical in each dimension!" when I use tomograms generated in WARP. But the template matching runs with IMOD generated tomos.

Thanks for pointing that out. There was a typo in that error it should say "Input volume" instead of tomogram for which I made a PR #32. But I also added some additional things so that lets the user now know whether the tomogram or template has unequal spacing. 

> I also get a warning when specifying --input-voxel-size-angstrom for pytom_create_template.py saying
>
> WARNING:root:Provided voxel size does not match voxel size annotated in input map.

pytom_create_template.py also raises an error if the spacing is incorrect, so if that was the issue you should have gotten a problem there. 

> I get this error "Input tomogram voxel spacing is not identical in each dimension!" when I use tomograms generated in WARP. But the template matching runs with IMOD generated tomos.

Very strange that the Warp tomogram would have different spacing :0

**Comment by McHaillet** [comment]
> Update: I used `alterheader tomo/JTL013_1_L04_ts_003.mrc_13.28Apx.mrc -cel 512,722,226` which changes the pixel size to 1,1,1 in the header. This overcomes the previous error and I only get a warning.
> 
> ```
> 
> > 
> > pytom_match_template.py  -t 50S_ref.mrc -m 50S_mask.mrc -v tomo/JTL014_1_L14_ts_003.mrc_rec.mrc -a tomo/JTL014_1_L14_ts_003.mrc.tlt --angular-search 7.00 --search-x 10 500 --search-y 10 710 --search-z 10 210  --voxel-size-angstrom  13.28 --low-pass 40 --high-pass 500 -g 0 --log info
> > WARNING: Provided voxel size does not match voxel size annotated in tomogram/template mrc.
> > 
> ```

Good that you managed to solve it.  Just make sure that you specific `--voxel-size-angstrom` (as you already did) for the template matching because it is needed for calculating low pass and high pass filters.

Out of curiosity what does IMODs `header` function give as output before you updated the cel ?

**Comment by hamid13r** [comment]
Actually, it is not that surprising since WARP does not generally handle headers well. 
The pixel size line was 13.28 13.28 13.28 and changing it to below solved the error. 

```
RO image file on unit   1 : tomo/JTL013_1_L04_ts_003.mrc_13.28Apx.mrc     Size=     326345 K

 Number of columns, rows, sections .....     512     722     226
 Map mode ..............................    2   (32-bit float)             
 Start cols, rows, sects, grid x,y,z ...    0     0     0     512    722    226
 Pixel spacing (Angstroms)..............   1.000      1.000      1.000    
 Cell angles ...........................   90.000   90.000   90.000
 Fast, medium, slow axes ...............    X    Y    Z
 Origin on x,y,z .......................    0.000       0.000       0.000    
 Minimum density ....................... -0.44656    
 Maximum density .......................  0.16302    
 Mean density ..........................   0.0000    
 RMS deviation from mean................   0.0000    
 tilt angles (original,current) ........   0.0   0.0   0.0   0.0   0.0   0.0
 Space group,# extra bytes,idtype,lens .        0        0        0        0

```

**Comment by McHaillet** [comment]
That is a bit strange, but I did notice a similar thing when comparing voxel size between templates and tomogram and added [a rounding in](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/blob/3755a0ecaf729356cd41b3658f312de3d6fbbf6d/src/pytom_tm/tmjob.py#L101). Basically there was a numerical difference after the 6th decimal point in the voxel size annotation. Something like that might be the case here as well and where I check for [identical size](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/blob/3755a0ecaf729356cd41b3658f312de3d6fbbf6d/src/pytom_tm/io.py#L85) could also round to some decimal points.

**Comment by hamid13r** [comment]
That is kind of strange. But I have seen different packages handling the voxel sizes in weird ways.

**Comment by McHaillet** [comment]
What does this print on the Warp MRC file? (replace with your tomogram file)

`python -c "import mrcfile; print(mrcfile.mmap('TOMOGRAM.MRC').voxel_size)"`

**Comment by hamid13r** [comment]
It took me a while to recreate the error since apparently it is not the case for all the tomograms!
```
python -c "import mrcfile; print(mrcfile.mmap('JTL014_1_L14_ts_002.mrc_13.28Apx.mrc').voxel_size)"
(13.28, 13.280001, 13.28)
```

Seems like that 0.000001 difference is the problem!
