### ISSUE TITLE
issues with reading mrc files

### ISSUE THREAD

**Issue by 3P1L** [SBC-Utrecht/pytom-template-matching-gpu#35]
Hey!

a) thank you for this update to pytom! I'm really excited to try GPU-accelerated TM!

b) I do not know why, but mrcfile complains when trying to read the header of our mrc files.

They work fine in any other program though ...

From the code, it appears that you use it to also get the size of the tomograms and hence I guess it cannot be avoided.

To fix this problem, the permissive statement is needed and hence I changed pytom_tm/io.py, line 79 to:

with mrcfile.mmap(file_name, **permissive=True**) as mrc:

which appears to fix the issue.

Best,

Philipp.

**Comment by McHaillet** [comment]
Hi Philipp, 

thanks for the issue report and suggested solution! I already added permissive for reading the mrc arrays, but not for the function that reads metadata. So it should be set to permissive as default. I made a pull request for it #38.

If you have an issue like this and proposed fix, feel free to make a pull request for it next time.

**Comment by 3P1L** [comment]
Hi Marten,

Haha - sorry I am not so good at Github 😅

Will do the pull request next time.

Best,

Philipp.


           
Philipp Sebastian Erdmann
Research Group Leader
Erdmann Group, 
Structural Biology Research Centre
Human Technopole
Palazzo Italia
Viale Rita Levi Montalcini, 1
20157 Milan, Italy
M. +39 3452453710
E. ***@***.***
Prima di stampare questa e-mail, pensa all’ambiente.
Before printing this e-mail, think of the environment
Legal Disclaimer 
The information contained in or accompanying this email and any attachment thereto, is intended solely for the use of the stated recipient(s) and may contain information that is confidential and/or privileged. Any dissemination, distribution or copying of this email and any attachment by anyone who is not the stated recipient is strictly prohibited. If you receive this message in error, please notify the sender immediately and delete the message and any attachment from your system without retaining a copy.
On 6 Sep 2023, at 11:49, Marten ***@***.******@***.***>> wrote:



Hi Philipp,

thanks for the issue report and suggested solution! I already added permissive for reading the mrc arrays, but not for the function that reads metadata. So it should be set to permissive as default. I made a pull request for it #38<https://github.com/SBC-Utrecht/pytom-template-matching-gpu/pull/38>.

If you have an issue like this and proposed fix, feel free to make a pull request for it next time.

**Comment by McHaillet** [comment]
A small correction like this is an excellent way to learn it ;)

**Comment by McHaillet** [comment]
Should be fixed now if you reclone the repo!
