### ISSUE TITLE
Adding tomogram masking option

### ISSUE THREAD

**Issue by hamid13r** [SBC-Utrecht/pytom-template-matching-gpu#36]
Hi, 

We are doing a large number of template matching jobs and often use Amira masks to limit particles to be inside the cell. In the previous version there was on option of adding a tomogram mask but it seems to be gone now. 

At the moment we are using imod clip to multiply the scores file to the mask before extraction, but have masks in the input of extraction could be much more convenient. 

Thanks,
Hamid

**Comment by McHaillet** [comment]
Hi Hamid,
Thanks for pointing it out, will add this in as soon as possible.
One question: are the masks you use always binary?

**Comment by hamid13r** [comment]
Thank you very much.

They usually are, but we have had a project with tri-color segmentation from Amira (0: ignore, 1: first area of interest, 2: second area of interest). If that could be implemented it would be extra-helpful, especially as segmentation tools become more automated.

**Comment by hamid13r** [comment]
We would want to be able to pick particles in one area only. This is not a very common occurrence and a binary mask (1: pick and 0: ignore) would be enough for 95% of the cases. Also we have tools to make desired masks from segmentations anyways.
