### ISSUE TITLE
Including the LCCmax in the star file

### ISSUE THREAD

**Issue by hamid13r** [SBC-Utrecht/pytom-template-matching-gpu#37]
As I mentioned previously in #36 , we often mask our tomograms to limit false positives and this throws off the distribtion of the score (local cross-correlation).  it would be extremely useful for us to have scores of each particle included in the output starfiles so we can manipulate the files later when we go through our picks. 

Thanks in advance,
Hamid

**Comment by McHaillet** [comment]
Valid point, will try to fix it soon. See issue #20

**Comment by McHaillet** [comment]
Hi Hamid, 
This is now added in, and the STAR file also contain a column with the CutOff and the SearchStd. Which can be used to express everything in a number of standard deviations, see the [wiki](https://github.com/SBC-Utrecht/pytom-template-matching-gpu/wiki/Extracting-particles)!
