### ISSUE TITLE
invalid resolution specified

### ISSUE THREAD

**Issue by DrJesseHansen** [SBC-Utrecht/pytom-template-matching-gpu#46]
hello, 

thanks for the great tools! 

I am trying to create a template.  I have used a PDB (and done molmap) and also tried downloading an EM density and both times I get the same error.  

First, when I check the header of my mrc input I get:
Pixel spacing (Angstroms)..............   1.693      1.693      1.693 

Now my command:
pytom_create_template.py -i emd_1.mrc -o template.mrc --input-voxel-size-angstrom 1.693 --output-voxel-size-angstrom 13.54

WARNING:root:Provided voxel size does not match voxel size annotated in input map.
WARNING:root:Invalid resolution specified, changing to 27.08A
INFO:root:Convoluting volume with filter and then downsampling.

No idea what's happening here.  Thanks in advance

Jesse

**Comment by McHaillet** [comment]
Hi Jesse,

I was on holidays the last weeks, so getting to your issue now.

If you run the following on your template with the conda environement active, 

``` python -c "from pytom_tm.io import read_mrc_meta_data; print(read_mrc_meta_data('emd_1.mrc')['voxel_size'])``` ,

you will probably see some small decimal point values that are not significant. So, you can safely skip the warning.

Anyway I will push a fix to make the warning a bit less stringent because it was giving errors before in another part of the code!

Best,
Marten

**Comment by McHaillet** [comment]
Both warnings have been solved with PR #47.

You can update your installation with the following. First activate your environment:

```
conda activate pytom_tm
```

Then go to the folder where you cloned the repo:

```
cd pytom-template-matching-gpu
```

Pull latest changes and reinstall:

```
git pull
pip install .[plotting]
```

**Comment by DrJesseHansen** [comment]
hi, just wanted to update that I had our IT dept install the latest version (I guess  pytom-template-matching-gpu/0.2-

pytom_create_template.py -i input_map.mrc -o template.mrc --input-voxel-size-angstrom 2.762 --output-voxel-size-angstrom 11.048 --center -c -z 5 -a 0.07 -v 300 --Cs 2.7 --cut-after-first-zero
WARNING:root:Resolution is either not specified (in which case you can ignore this warning) or incorrectly specified, changing to 22.096A
INFO:root:Convoluting volume with filter and then downsampling.

**Comment by McHaillet** [comment]
Hi, sorry I do not understand what the issue is now. You are getting an output volume, right?

The minimal resolution for the low pass filter is calculated as `2 * output_voxel_size` and is applied before downsampling to prevent aliasing. The WARNING does not mean that the program errored out. (Perhaps its better if its just an info line though.)

**Comment by DrJesseHansen** [comment]
hi,
yes I did get an output volume.  Just got the error.  Not sure it's a big deal, just figured I would mention it.   Thanks again for the great program!  

While I have you here, can I quickly ask: since my tomograms all have different defoci, should I generate different templates to match each tomogram (or at least roughly group them together into defoci range)?

**Comment by McHaillet** [comment]
You can ignore the warning!

I will respond to that in the other issue (just to keep it organised :) )

@sroet  should I just make it an info print to remove confusion?

**Comment by sroet** [comment]
> @sroet should I just make it an info print to remove confusion?

We should probably have a catch that knows if it was not provided and print info, and one that sets it if it was incorrectly specified that prints an warning. It should probably also be a bit more verbose about the fact that this is the resolution for the lowpass filter, not the input/output/matching

**Comment by McHaillet** [comment]
this is the line: https://github.com/SBC-Utrecht/pytom-template-matching-gpu/blob/3cba28469bce599b5bab8c4bd8d96baa27ae8ccd/src/pytom_tm/template.py#L40
