### ISSUE TITLE
question about non-spherical mask

### ISSUE THREAD

**Issue by DrJesseHansen** [SBC-Utrecht/pytom-template-matching-gpu#49]
hi,

I apologize for so many questions!  I really love pyTOM but am having a hard time getting ideal results.  Is this the best way to communicate with you or is it better to email, for e.g.?  

Two questions this time:
1) Can you please confirm that the mask signal is opposite the template/tomogram (e.g. tomo signal black, template signal black, mask signal white)?

2) My template has a weird shape: it is F-actin bound to an actin-binding protein.  So in my template box the actin extends all the way to the edges.  I tried an oval mask and it worked okay ish (based on RUC value).  However I tried a mask that is tighter and was generated from the template itself, extended outward, and added a soft edge.  However this seems to give worse results than an oval and I don't understand why.  the RUC is non NaN, and estimated number of positives is zero.  Any thoughts on why this might be happening?

thanks in advance! 

Jesse

**Comment by McHaillet** [comment]
> Can you please confirm that the mask signal is opposite the template/tomogram (e.g. tomo signal black, template signal black, mask signal white)?

Yep that is correct!

> My template has a weird shape: it is F-actin bound to an actin-binding protein. So in my template box the actin extends all the way to the edges. I tried an oval mask and it worked okay ish (based on RUC value). However I tried a mask that is tighter and was generated from the template itself, extended outward, and added a soft edge. However this seems to give worse results than an oval and I don't understand why. the RUC is non NaN, and estimated number of positives is zero. Any thoughts on why this might be happening?

Did you set the non-spherical-mask flag ? Just to double check

**Comment by DrJesseHansen** [comment]
hi, thanks.  Yes I did set that flag.  I think the issue is the gold fiducials.  I am currently trying to erase those.

**Comment by McHaillet** [comment]
issue #50 is now about the gold beads

**Comment by McHaillet** [comment]
Closing: gold bead removal is not on to-do anymore and is recommend to do in IMOD
