### ISSUE TITLE
Tutorial: images

### ISSUE THREAD

**Issue by jmdobbs** [SBC-Utrecht/pytom-template-matching-gpu#70]
Hi,

Thanks for all the great work on pyTOM and the continued updates. I had a quick look at the nice tutorial you posted and see that the images -for me, at least- are broken. This is both on firefox and edge. May be a problem with my computer but might also be worth looking into.

Thanks!
Joe

**Comment by McHaillet** [comment]
Hi Joe, Thanks a lot for notifying us! We are fixing it :)

**Comment by sroet** [comment]
@jmdobbs It is solved locally for me, can you confirm the images are now properly included in the tutorial?

**Comment by jmdobbs** [comment]
@sroet Looks good to me as well! Thanks :)
